<template>
  <div class="holder tracking-in-contract-bck-bottom">
    <div
      class="ui-card ui-card--shadow-always"
      v-for="(card, index) in paginatedData"
      :key="index"
      @click="onClick(card)"
    >
    <div class="image-wrapper ">
      <img :src="card.pics[0]" alt="" srcset="" />
      </div>
      <p class=".ui-text-small center">{{ card.title }}</p>
      <p class="ui-title-3">{{ Math.floor(card.price * 1.18) }} <span class="currency">{{card.currency}}</span></p>
      <p>{{ card.Производитель }}</p>
      <!-- modal -->
      <a-modal v-model="visible" :title="ProdObject.title" on-ok="handleOk">
        <template slot="footer">
          <a-button key="back" @click="handleCancel">
            Return
          </a-button>
          <a-button key="submit" type="primary" @click="handleOk1">
            Добавить в корзину
          </a-button>
        </template>
        <!-- carousel -->
        <div class="carousel-wrapper">
          <a-carousel autoplay arrows>
          
            <div
              class="image-holder"
              v-for="(pic, index) in ProdObject.imageArr"
              :key="index"
            >
              <img class="prodimg" :src="pic" />
            </div>
          </a-carousel>
        </div>
        <!-- end carousel -->
        <div class="modal__description" v-html="ProdObject.description"></div>
        <p class="modal__price">{{ `${Math.floor(ProdObject.price)} UAH` }}</p>
      </a-modal>
      <!-- end modal -->
    </div>

    <div class="nav-content">
      <div
        class="button button--plain button-primary"
        v-show="pageNumber > 0"
        @click="prevPage"
      >
        PREV
      </div>
      <div
        class="button button--plain button-success"
        v-show="pageNumber < pageCount - 1"
        @click="nextPage"
      >
        NEXT
      </div>
    </div>
  </div>
</template>

<script>
import "../styles/CradStyles.scss";
export default {  
  data() {
    return {
      pageNumber: 0,
      timeOut: 0,
      visible: false,
      ProdObject:{'image': "",'imageArr': "", 'article': "", 'title': "", 'price': "", 'description': "" },
     };
  },
  components: {},
  props: {
    CardData: {
      type: Array,
      required: true,
    },
    size: {
      type: Number,
      required: false,
      default: 20,
    },
  },
  methods: {
    showModal() {
      this.visible = true;
    },
    handleOk1() {
      this.loading = true;
      setTimeout(() => {
        this.visible = false;
        this.loading = false;
      }, 1000);
      this.$store.commit('AddItem', this.ProdObject);
      console.log(this.$store.state.basketItems.length);
    },
    handleCancel() {
      this.visible = false;
      localStorage.clear();
    },
    handleOk() {
      this.visible = false;
    },
    nextPage() {
      this.pageNumber++;
      this.goUp();
    },
    prevPage() {
      this.pageNumber--;
      this.goUp();
    },
    onClick(item) {
      this.ProdObject={
        image: item.pics[0],
        imageArr: item.pics,
        article: item.id,
        title: item.title,
        price: item.price * 1.18,
        description: item.description
      },     
      this.showModal();
    },
    goUp() {
      let top = Math.max(
        document.body.scrollTop,
        document.documentElement.scrollTop
      );
      if (top > 0) {
        window.scrollBy(0, -2000);
        this.timeOut = setTimeout("goUp()", 20);
      } else clearTimeout(this.timeOut);
    },
  },

  computed: {
    pageCount() {
      let l = this.CardData.length,
        s = this.size;
      return Math.ceil(l / s);
    },
    paginatedData() {
      let start = this.pageNumber * this.size,
        end = start + this.size;
      let arr = this.CardData.slice(start, end);
      for (let i = 0; i < arr.length; i++) {
        var arrayOfStrings = arr[i].Ссылка_изображения.split(",");
        arr[i].pics = arrayOfStrings;
      }
      return arr;
    },
   
  },
};
</script>

<style lang="css" scoped>
.tracking-in-contract-bck-bottom {
	-webkit-animation: tracking-in-contract-bck-bottom 1s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        animation: tracking-in-contract-bck-bottom 1s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-2-2 23:7:21
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tracking-in-contract-bck-bottom
 * ----------------------------------------
 */
@-webkit-keyframes tracking-in-contract-bck-bottom {
  0% {
    letter-spacing: 1em;
    -webkit-transform: translateZ(400px) translateY(300px);
            transform: translateZ(400px) translateY(300px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0) translateY(0);
            transform: translateZ(0) translateY(0);
    opacity: 1;
  }
}
@keyframes tracking-in-contract-bck-bottom {
  0% {
    letter-spacing: 1em;
    -webkit-transform: translateZ(400px) translateY(300px);
            transform: translateZ(400px) translateY(300px);
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    -webkit-transform: translateZ(0) translateY(0);
            transform: translateZ(0) translateY(0);
    opacity: 1;
  }
}

</style>
