<template>
  <div class="holder">
    <ul class="sidebar-list">
      <li
        class="sidebar-item slide-in-left"
        v-for="(title, index) in SideBarData"
        v-bind:key="index"
        @click="active = active === title ? null :title"
      >
        <span v-on:click="text" :id="title.ID" :class="active === title ? 'active' : ''">{{ title.Title }}</span>
        <hr noshade />
      </li>
    </ul>
  </div>
</template>

<script>
import "../styles/SideBarStyles.scss"

export default {
data(){
  return{
active: null,
  };
},
  props: ["SideBarData"],
  methods: {
    text: function(params) {
      console.log(params.target.id);
      this.$store.commit('SetGroup', params.target.id);
      console.log(this.$store.state.groupID);
      
    }
  }
};
</script>

<style lang="css" scoped>
.slide-in-left {
	-webkit-animation: slide-in-left 2s ;
	        animation: slide-in-left 2s ;
}
/* ----------------------------------------------
 * Generated by Animista on 2021-2-2 23:10:40
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}

</style>

